site_name: Catepila Development
site_url: https://catepilladevelopment.github.io/
nav:
  - Home: index.md
  - Requirements: req.md
  - Architecture: arch.md
  - Planning: planning.md
  - Risk Assessment: risk.md
  - Implementation: imp.md
theme:
  name: material
  logo: img/catepila_head.png
  favicon: img/catepila_head.png
  font:
    text: Comic Sans
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
extra:
  generator: false
